import type { ReactElement } from "react";

import Head from "next/head";
import Image from "next/image";

// ** Algolia Imports **
import algoliasearch from "algoliasearch";
import {
  InstantSearch,
  SearchBox,
  InfiniteHits,
  Configure,
} from "react-instantsearch-hooks-web";

import ArticleCard from "../../components/Public/Articles/ArticleCard/ArticleCard";
import UserLayout from "../../layouts/UserLayout";

export default function Articles() {
  const searchClient = algoliasearch(
    process.env.NEXT_PUBLIC_ALGOLIA_APPLICATION_ID as string,
    process.env.NEXT_PUBLIC_ALGOLIA_SEARCH_ONLY_API_KEY as string
  );

  return (
    <>
      <Head>
        <title>Articles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <InstantSearch
        searchClient={searchClient}
        indexName={
          process.env.NEXT_PUBLIC_ALGOLIA_ARTICLES_INDEX_NAME as string
        }
      >
        <Configure analytics={true} hitsPerPage={6} />
        <section className="relative container mx-auto scroll-smooth max-w-8xl px-6 md:px-0">
          <div className="px-8 md:px-16 lg:px-14 py-14 mb-8 md:mb-16 bg-indigo-200 border-4 border-indigo-900 shadow-md rounded-2xl relative overflow-hidden">
            <Image
              src="/banner-right.svg"
              alt="Bg"
              width={500}
              height={500}
              className="absolute top-0 md:h-full right-0 w-1/2 lg:w-1/3 opacity-60"
            />
            <Image
              src="/banner-left.svg"
              alt="Bg"
              width={500}
              height={500}
              className="absolute top-0 md:h-full left-0 w-1/2 lg:w-1/3 opacity-60"
            />
            <div className="container px-4 relative">
              <div className="max-w-6xl mx-auto">
                <span className="text-md md:text-lg text-left font-extrabold text-indigo-500">
                  AWESOME
                </span>
                <h1 className="text-4xl lg:text-5xl font-extrabold font-heading mt-4 mb-8 text-black border-b-4 border-indigo-900 max-w-lg pb-6">
                  Articles
                </h1>
                <SearchBox
                  placeholder={"Search for Awesome Articles"}
                  searchAsYouType={false}
                  submitIconComponent={() => null}
                  resetIconComponent={() => null}
                  classNames={{
                    root: "inline-flex w-full max-w-lg p-1 items-center bg-white border-2 border-indigo-900 rounded-xl shadow bg-opacity-80",
                    input:
                      "w-full bg-transparent text-lg font-extrabold text-indigo-900 placeholder-indigo-900 border-none outline-none text-[16px] md:text-[18px]",
                    form: "w-full",
                  }}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="mb-16 md:mb-24">
          <div className="container mx-auto px-6 md:px-0">
            <InfiniteHits
              showPrevious={false}
              //eslint-disable-next-line
              //@ts-ignore
              hitComponent={(e) => <ArticleCard hits={e.hit} />}
              classNames={{
                list: "grid sm:grid-cols-1 md:grid-cols-4 lg:grid-cols-3 gap-8",
                item: "w-full sm:col-span-1 md:col-span-2 lg:col-span-1 mb-4 ",
                loadMore:
                  "w-full mt-12 mx-auto text-center inline-block py-4 px-12 text-center leading-6 text-lg text-white font-extrabold bg-indigo-800 hover:bg-indigo-900 border-3 border-indigo-900 shadow rounded transition duration-200",
                disabledLoadMore: "hidden",
              }}
            />
          </div>
        </section>
      </InstantSearch>
    </>
  );
}

Articles.getLayout = function getLayout(page: ReactElement) {
  return <UserLayout>{page}</UserLayout>;
};
