import type { ReactElement } from "react";

import Head from "next/head";

// **Custom Components
import Banner from "../components/Public/Home/Banner/Banner";
import Categories from "../components/Public/Home/Categories/Categories";
import SubmitProject from "../components/Public/Home/SubmitProject/SubmitProject";
import LatestArticles from "../components/Public/Home/LatestArticles/LatestArticles";
import Socials from "../components/Public/Home/Socials/Socials";

import UserLayout from "../layouts/UserLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Awesome Polka</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Banner />
      <Categories />
      <SubmitProject />
      <LatestArticles />
      <Socials />
    </>
  );
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <UserLayout>{page}</UserLayout>;
};
