// ** Next Imports
import Head from "next/head";
import { useRouter } from "next/router";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Image from "next/image";

import { useState } from "react";

// ** Amplify Imports
import { API, graphqlOperation, withSSRContext } from "aws-amplify";
import { getProject } from "../../../graphql/queries";
import { ProjectStatus } from "../../../API";

// ** Types
import { Project } from "../../../API";

// ** Icon Imports
import {
  FolderIcon,
  HomeIcon,
  UsersIcon,
  DocumentTextIcon,
  QuestionMarkCircleIcon,
  BriefcaseIcon,
} from "@heroicons/react/24/outline";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

import { faCaretUp } from "@fortawesome/free-solid-svg-icons";

export const getServerSideProps: GetServerSideProps<{
  data: Project;
}> = async (context) => {
  const SSR = withSSRContext();

  const data = await SSR.API.graphql(
    graphqlOperation(getProject, {
      id: context.params?.name,
    })
  );

  //TODO: Change approved to not approved
  if (
    data.data.getProject === null ||
    data.data.getProject.status === ProjectStatus.APPROVED
  ) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data: data.data.getProject,
    },
  };
};

export default function ProjectDetail({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const router = useRouter();

  const [navigation, setNavigation] = useState([
    {
      name: "Project Detail",
      href: "#description",
      icon: HomeIcon,
      current: false,
    },
    {
      name: "Token Stats",
      href: "#token-stats",
      icon: UsersIcon,
      current: false,
    },
    {
      name: "GitHub Activity",
      href: "#github-activity",
      icon: FolderIcon,
      current: false,
    },
    { name: "Team", href: "#team", icon: UsersIcon, current: false },
    {
      name: "Articles",
      href: "#articles",
      icon: DocumentTextIcon,
      current: false,
    },
    { name: "FAQ", href: "#faq", icon: QuestionMarkCircleIcon, current: false },
    {
      name: "Job Openings",
      href: "#jobs",
      icon: BriefcaseIcon,
      current: false,
    },
  ]);

  // If the page is not yet generated, this will be displayed
  // initially until getStaticProps() finishes running
  if (router.isFallback) {
    return <div>Loading...</div>;
  }

  // @ts-ignore
  function classNames(...classes) {
    return classes.filter(Boolean).join(" ");
  }

  // @ts-ignore
  function handleClick(item) {
    // @ts-ignore
    if (item.href) {
      navigation.forEach((item) => {
        item.current = false;
      });
      // @ts-ignore
      const index = navigation.findIndex((x) => x.href === item.href);
      // @ts-ignore
      const newNavigation = [...navigation];
      // @ts-ignore
      newNavigation[index].current = true;
      setNavigation(newNavigation);
    }
  }

  function handleVote() {
    console.log("Voted");
  }

  return (
    <>
      <Head>
        <title>{data.name} - Awesome Lens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
    </>
  );
}
