import Head from "next/head";
import Image from "next/image";

import Table from "../../components/user/Ranking/Table/Table";

export default function Ranking() {
  return (
    <>
      <Head>
        <title>Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="relative container mx-auto scroll-smooth max-w-8xl px-6 md:px-0">
        <div className="px-8 md:px-16 lg:px-14 py-14 mb-8 md:mb-16 bg-indigo-200 border-4 border-indigo-900 shadow-md rounded-2xl relative overflow-hidden">
          <Image
            src="/banner-right.svg"
            alt="left-bg-banner"
            className="absolute top-0 md:h-full right-0 w-1/2 lg:w-1/3 opacity-60"
            width={500}
            height={500}
          />
          <Image
            src="/banner-left.svg"
            alt="left-bg-banner"
            className="absolute top-0 md:h-full left-0 w-1/2 lg:w-1/3 opacity-60"
            width={500}
            height={500}
          />
          <div className="container px-4 relative">
            <div className="max-w-6xl mx-auto">
              <span className="text-md md:text-lg text-left font-extrabold text-indigo-500">
                AWESOME
              </span>
              <h1 className="text-4xl lg:text-5xl font-extrabold font-heading mt-4 mb-8 text-black">
                Ranking
              </h1>
              <p className="text-lg md:text-xl font-semibold leading-7 border-t-4 border-indigo-900 pt-6 max-w-lg">
                Discover the top performers in Aave ecosystem with our
                comprehensive rankings.
              </p>
              <div className="max-w-2xl mx-auto"></div>
            </div>
          </div>
        </div>
      </section>
      <Table />
    </>
  );
}
