import type { ReactElement } from "react";

import Head from "next/head";
import Image from "next/image";

import Table from "../../components/Public/Ranking/Table/Table";
import { ExclamationTriangleIcon } from "@heroicons/react/20/solid";

import UserLayout from "../../layouts/UserLayout";

export default function Ranking() {
  return (
    <>
      <Head>
        <title>Ranking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <section className="relative container mx-auto scroll-smooth max-w-8xl px-6 md:px-0">
        <div className="px-8 md:px-16 lg:px-14 py-14 mb-8 md:mb-16 bg-indigo-200 border-4 border-indigo-900 shadow-md rounded-2xl relative overflow-hidden">
          <Image
            src="/banner-right.svg"
            alt="left-bg-banner"
            className="absolute top-0 md:h-full right-0 w-1/2 lg:w-1/3 opacity-60"
            width={500}
            height={500}
          />
          <Image
            src="/banner-left.svg"
            alt="left-bg-banner"
            className="absolute top-0 md:h-full left-0 w-1/2 lg:w-1/3 opacity-60"
            width={500}
            height={500}
          />
          <div className="container px-4 relative">
            <div className="max-w-6xl mx-auto">
              <span className="text-md md:text-lg text-left font-extrabold text-indigo-500">
                AWESOME
              </span>
              <h1 className="text-4xl lg:text-5xl font-extrabold font-heading mt-4 mb-8 text-black">
                Ranking
              </h1>
              <p className="text-lg md:text-xl font-semibold leading-7 border-t-4 border-indigo-900 pt-6 max-w-lg">
                Discover the top performers in Polkadot ecosystem with our
                comprehensive rankings.
              </p>
              <div className="max-w-2xl mx-auto"></div>
            </div>
          </div>
        </div>
      </section>
      {/* <Table /> */}
      <section className="relative container mx-auto scroll-smooth max-w-8xl px-6 md:px-0 mb-24">
        <button
          type="button"
          className="relative block w-full rounded-lg border-2 border-dashed border-indigo-300 p-6 text-left hover:border-indigo-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 cursor-none"
        >
          <div className="rounded-md bg-yellow-50 p-8">
            <div className="flex">
              <div className="flex-shrink-0">
                <ExclamationTriangleIcon
                  className="h-5 w-5 text-yellow-400"
                  aria-hidden="true"
                />
              </div>
              <div className="ml-3">
                <h3 className="text-sm font-medium text-yellow-800">
                  Under Construction
                </h3>
                <div className="mt-2 text-sm text-yellow-700">
                  <p>
                    Ranking feature will be available soon. Please stay tuned!
                  </p>
                </div>
              </div>
            </div>
          </div>
        </button>
      </section>
    </>
  );
}

Ranking.getLayout = function getLayout(page: ReactElement) {
  return <UserLayout>{page}</UserLayout>;
};
